spring.application.name=AUTH-SERVICE

server.port=8080

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.lease-renewal-interval-in-seconds=10
#eureka.instance.lease-expiration-duration-in-seconds=15

spring.datasource.url=jdbc:postgresql://192.168.2.254:5432/auction_db
spring.datasource.username=auction_user
spring.datasource.password=auction123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none 
#update
spring.jpa.show-sql=true

jwt.secret=mySuperSecretKeyForJwtTokenGeneration123456789
#jwt.expiration=86400000
jwt.accessTokenExpiration=3600000
jwt.refreshTokenExpiration=604800000

# SendGrid SMTP Server Settings
# 1. Connect Directly to Google Servers
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testgms02@gmail.com
spring.mail.password=bahphsatophyjiid

# 2. Strict TLS Authentication Rules for Google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# 3. Matches your authenticated user
app.mail.from=testgms02@gmail.com

twilio.account-sid=ACf5ea6c2e29adabe17ff8fd37a909dff5
twilio.auth-token=4aac40323dcaad45f4ff7a3d69ca2a31
twilio.sms-sender=+19516293405
twilio.whatsapp-sender=+14155238886
